version: '3.7'

services:
  mailcatcher:
    container_name: mailcatcher
    image: jeanberu/mailcatcher
    environment:
      - SMTP_PORT=1025
      - HTTP_PORT=1080
    ports:
      - "1025:1025"
      - "1080:1080"
