name: Trivy Scan

on:
  pull_request:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'aio_send_dir/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      - name: Run Trivy vulnerability scanner on filesystem
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 #v0.36
        with:
          scan-type: "fs" # Scan the file system
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
